### ISSUE TITLE
Viet Anh - BE: Customer cart management

### ISSUE THREAD

**Issue by UpperMoon0** [KhoaWorkHub/Diamond-Shop-System-SWP391-SE1840-Group6#23]
Branch: customer-cart

Path to files:

- <diamond_shop>: be/src/main/java/vn/fpt/diamond_shop
- CustomerController class: <diamond_shop>/controller/CustomerController
- Cart class: <diamond_shop>/model/Cart
- ECartRequestType enum: <diamond_shop>/constant/ECartRequestType
- CartRequest class: <diamond_shop>/model/dto/CartRequest
- GetCartResponse class: <diamond_shop>/model/dto/GetCartResponse 

Requirements:

- **You should only edit the CustomerController and Cart classes.**
- Assuming a customer can only buy 1 of each jewelry type / model, so no need to handle quantity of jewelry with the same type / model.
- In the Cart class, it's already set to session scope. You need to implement a way to store jewelry entities in the cart. The cart also needs these methods: add, remove, removeAll, and get (this method returns the content of the cart).
- In the CustomerController class, you need to implement the methods to process the CartRequest and perform the cart operations.

**Comment by Vietanh2703** [comment]
An update for my function will be released on Sunday 16/06/2024

**Comment by UpperMoon0** [comment]
Okay, but don't close this issue yet.

**Comment by UpperMoon0** [comment]
I'd like you to integrate your customer cart feature into the customer-cart branch. Because your works is done on a separate project, it's not possible to merge.
